---
title: "NONMEM/PsN/qpsn/R testing"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup, include=F}
## DO NOT MODIFY THIS BLOCK (unless you know what you're doing)
library(rprojroot)
library(knitr)
opts_chunk$set(echo=F)
opts_knit$set(root.dir=find_root(has_file(".Rprofile")))
opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE,message=FALSE}
library(future)
future::plan("future::multiprocess", workers = 2)
library(NMproject)
library(dplyr)
devtools::load_all("~/NMproject/")
load_localpackage()
module_cmd("module load psn/4.4.8-foss-2017a-gfortran-5.2-b1")
```


## First set of 6 runs

These are all single core

```{r}
ds <- tibble(run_id = 1:6)  ## runs 1 to 6 to be run single core

ds$m <- nm2(run_id = ds$run_id) %>%
  based_on("staging/Models/run{run_id}.mod") %>%
  cmd("qpsn -t 100 -r 1000 -- execute run{run_id}.mod -dir={run_dir}")

#nm_tran(ds$m)

# ds$m <- ds$m %>% run_nm()
# ds$m <- ds$m %>% update_parameters()
# ds$m <- ds$m %>% run_nm()

ds %<-% {
  ds %>% mutate(m = m %>% run_nm() %>%
                  update_parameters() %>%
                  run_nm() %>%
                  wait_finish(timeout = 20*60)) ## wait max of 20 mins
}

summary(ds$m) %>% 
  select(run_id, status, ofv:cond_num)

## gof plot of first run
pl <- ds$m[1] %>% gof_ggplot2()
pl

pl2 <- plot_job_run_times_nm(ds$m)
pl2[[6]]

ds$m[1] <- ds$m[1] %>% 
  nmsave_plot(pl, plot_name = "gof_{run_id}.pdf") %>%
  nmsave_plot(pl, plot_name = "gof_{run_id}.png")

ds$m <- ds$m %>% 
  nmsave_plot(pl2[[6]], plot_name = "run_times_1:6.png")

```

## repeat run6 100s of times

```{r}

d6 <- tibble(rep = 1:100) ## 500
d6$run_id <- paste0("6_", d6$rep)

d6$m <- ds$m[6] %>% child(run_id = d6$run_id) %>%
  run_in("Models/reptest") %>%
  cmd("qpsn -c auto -t 3000 -r 1000 -- execute run{run_id}.mod -dir={run_dir}")

#nm_tran(d6$m[1:2])

d6 %<-% {
  d6 %>% mutate(m = m %>% run_nm() %>%
                    wait_finish(timeout = 120*60)) ## 120 mins
}

####### summary test

s6 <- summary(d6$m) 

status_table(d6$m)

s6 %>% select(run_id, status, ofv:cond_num) %>% head(10)

p62 <- plot_job_run_times_nm(d6$m)
p62[[6]]

d6$m %>%
  nmsave_table(status_table(d6$m), "d6_run_status.csv") %>%
  nmsave_plot(p62[[6]], "d6_run_times.png")

```

## repeat run6 with different numbers of cores

```{r}

dc %<-% {
  tibble(cores = 1:36) %>%
    mutate(m = ds$m[6] %>% child(run_id = cores) %>%
             cmd("qpsn -c {run_id} -t 1000 -r 1000 -- execute run{run_id}.mod -dir={run_dir}") %>%
             run_in("Models/coretest") %>%
             run_nm() %>%
             wait_finish(timeout = 60*60)) ## 1 hour
}

sc <- summary(dc$m) 

status_table(dc$m)

sc %>% select(run_id, status, ofv:cond_num) %>% head(5)

pl <- plot_job_run_times(jobs = job_info(dc$m),
                         run_in = run_in(dc$m))
## print pl[[6]]

dc$m %>%
  nmsave_table(status_table(dc$m), "dc_run_status.csv") %>%
  nmsave_plot(pl[[6]], "dc_run_times.png")

pl[[6]]

```

## run a bootstrap

```{r}
m1boot %<-% {
  ds$m[1] %>% child(run_id = "m1boot", type = "bootstrap") %>%
  cmd("qpsn -c 5 -t 1000 -r 1000 -- bootstrap run{run_id}.mod -samples=100 -threads=20 -dir={run_dir}") %>%
  run_nm() %>%
  wait_finish()
}

status_table(m1boot)

```



