    MODULE PRSIZES
        INTEGER, PARAMETER :: ISIZE=SELECTED_INT_KIND(8)
        INTEGER, PARAMETER :: DPSIZE=SELECTED_REAL_KIND(8)
        INTEGER, PARAMETER :: PE=4
        INTEGER, PARAMETER :: MAXRECID=200
        INTEGER, PARAMETER :: PC=30
        INTEGER, PARAMETER :: PCT=1
        INTEGER, PARAMETER :: PIR=1
        INTEGER, PARAMETER :: PD=35
        INTEGER, PARAMETER :: PAL=50
        INTEGER, PARAMETER :: MAXFCN=1000000
        INTEGER, PARAMETER :: MAXIC=90
        INTEGER, PARAMETER :: PG=80
        INTEGER, PARAMETER :: PES=1
    END MODULE PRSIZES
