---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
source(".Rprofile")
```
# {{{ Package }}}

<!-- badges: start -->
<!-- badges: end -->

Version: See DESCRIPTION file

## Objective

The goal of {{{ Package }}} is to ...

## Directory structure

- **`r NMproject::nm_dir("scripts")`**: Location of Script files for data cleaning, analysis and post-processing.
- **`r NMproject::nm_dir("models")`**: Location of model files (e.g. NONMEM, Stan, ...).
- **R**: Location of any custom R functions used in scripts.  These can be loaded with `devtools::load_all()` or by sourcing indivdiually via `source("R/functionname.R")`.
- **`r NMproject::nm_dir("results")`**: Location of Results files
- **`r NMproject::nm_dir("source_data")`**: Location of unmodified source datasets
- **`r NMproject::nm_dir("derived_data")`**: Location of analysis-ready datasets.  The production of these should be scripted.

## Data sources

The data was obtained from ...

<!--

Include links to databases and contact points to ensure this step can be traced.

-->

## Instructions to reproduce analysis

<!-- 

It is recommended to use a package management system (like renv) for all non-exploratory analysis that may need to be reproduced at future dates

-->

## More information

