---
output:
  html_notebook: default
title: "data processing"
author: "`r Sys.info()['user']`"
date: "`r Sys.time()`"
---


```{r setup, include=F}
## DO NOT MODIFY THIS BLOCK (unless you know what you're doing)
library(rprojroot)
library(knitr)
opts_knit$set(root.dir=find_root(has_file('.Rprofile')))
opts_chunk$set(echo = TRUE)
opts_chunk$set(message = TRUE)
```

```{r echo=FALSE,message=FALSE}
## LOAD PACKAGES HERE
library(NMproject)
library(dplyr)
library(future)
future::plan("future::multiprocess", workers = 2)

load_localpackage()
```

- Read THEOPP.csv from SourceData
- modify WT column so it's filled in for obs rows
- save into DerivedData

```{r}

d <- read.csv("SourceData/THEOPP.csv", na = ".")
kable(head(d, 20))

```

```{r}

d <- d %>%
  group_by(ID) %>%
  mutate(WT = na.omit(WT))

d %>% write_derived_data("data") ## DerivedData/data.csv

```


```{r}
## Define STRATA (no spaces)

d <-d %>%
  mutate(IDGRP = ID <= 6,
         WT_C = factor(Hmisc::cut2(WT, g = 2, levels.mean = TRUE)),
         STRATA = paste(IDGRP, WT_C, sep = "_"))

d_id <- d %>% distinct(ID, STRATA)

set.seed(123)

## create large set of resamples (to enable simulation to grow without ruining seed)
bootsplits <- rsample::bootstraps(d_id, 1000, strata = "STRATA")

bootsplits %>% saveRDS("DerivedData/bootsplit_data.csv.RData")

```


